site_name: Yao Group Projects

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Home:
    - docs/index.md
  - Manifold fitting:
    - docs/mf/index.md
  - Principal flow:
    - docs/pf/index.md