site_name: Yao Group Projects
site_url: https://zhigang-yao.github.io/group-projects/
site_description: >-
  We engage in the interaction between statistics and geometry

home_name: Yao Group Page
copyright: Copyright &copy; 2024 Yao Group Members. ALL RIGHTS RESERVED.

theme:
  name: material
  custom_dir: material/.overrides
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
  palette:
    - primary: custom
    - accent: cyan

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    repo: material/home-circle

repo_url: https://zhigang-yao.github.io/
repo_name: Back to homepage

extra_css:
  - assets/css/extra.css
  - assets/css/card-href.css

extra_javascript:
  - assets/js/mathjax.js
  - assets/js/lastupdate.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
extra:
  generator: false

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


nav:
  - Home: index.md
  - Research Focuses:
    - research/index.md
    - Theories:
      - pf/index.md
      - mf/index.md
      - sub/index.md
      - fbf/index.md
      - pb/index.md
    - Applications:
      - mfcgan/index.md
      - scamf/index.md
      - cellscope/index.md
      - ukb-meta/index.md
      - ukb-pancreas/index.md
      - ukb-missing/index.md
  - Privatissimum:
      - pri/index.md