site_name: Yao Group Projects

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Home: index.md
  - Manifold fitting: mf/index.md
  - Principal flow: /pf/index.md